[package]
name = "rustsimulationservice"
version = "0.1.0"
authors = ["Marcus Edwards <marcus@quantumemulation.ca>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
bit-vec = "0.5.0"
dotenv = "0.14.1"
amiquip = "0.3.0"
qasm = "1.0.0"
openssl = { version = "0.10", features = ["vendored"] }